### PR TITLE
Fixes media.original sending url before empty shape

### LINKED ISSUE #52: [270] Return original.url if sizes is missing
Sometimes, the REST API can return media with no sizes, like this:
```js
{
    id: 3733,
    ...
    media_details: {
        wp_kraken: "Compressed (saved 6943 bytes)",
        sizes: { },
    },
    source_url: "https://domain.com/wp-content/uploads/collar-electrico.jpg",
    },
}
```

Right now, if there's no `width`, `height` and `filename` in `media_details` and sizes is empty, it doesn't return the url.

https://github.com/frontity/wp-org-connection/blob/dev-stable/src/pwa/stores/connection/entity.js#L205

We should at least return the url before returning the `originalShape`.

Affected urls:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A18
(images 3730 and 3733)

Also, if any of this fields fails, the image shouldn't be returned because it will generate invalid AMP html. This can happen when no media is retrieved and the values are taken from the media shape.

----

https://frontity.pipedrive.com/deal/54

Pageviews: **(0.18)**
Environment: **production (x10)**
Range: **low (x1)**
Behaviour: **no frontity without it (x10)**
Mass: **everyone (x5)**
Referrer: **yes (x3)**
PRIORITY: **[270]**

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/wp-org-connection/issues/52

### CODE REVIEW

**Comment by orballo** [comment]
@DAreRodz ready for review 😄

File: src/pwa/stores/connection/entity.js [hunk 1]
```diff
@@ -168,8 +168,9 @@ const media = self => {
         }, []);
 
         // If there are no reduced sizes use src and original width.
-        if (!reducedSizes.length) return `${self.src} ${self.original.width}w`;
-
+        if (!reducedSizes.length) {
+          return self.src ? `${self.src} ${self.original.width || 100}w` : '';
```
Comment (DAreRodz) [inline src/pwa/stores/connection/entity.js]: Isn't it better to return `null` instead of an empty string so you don't need to check it [here](https://github.com/frontity/saturn-theme/pull/202/files#diff-481da6caaf7399c48f652d0caa8382baR58)?

**Comment by orballo** [comment]
@DAreRodz changes committed, ready for review 😄

**Review by DAreRodz — APPROVED** [review]
